#!/bin/bash

if [[ $1 == "configure" ]]; then
	
	if [ -e /sbin/initctl ]; then
#		cp -a --remove-destination /tmp/init/* /etc/init/ > /dev/null 2>&1
		initctl reload-configuration
		insserv -r /etc/init.d/xbmc > /dev/null 2>&1
		chmod -x /etc/init.d/xbmc > /dev/null 2>&1
	elif [ -f "/tmp/startxbmc" ]; then
		start xbmc 1>/dev/null 2>/dev/null >/dev/null
		rm /tmp/startxbmc
	fi

fi
